Current chat tabs container
AndresEstebanGonzalez/Whatsapp_Web pull request #1
Opened 2023-08-11 15:40 UTC by AndresEstebanGonzalez

2023-08-15 14:02 UTC, nathan-hyan requested changes
Great job, some changes

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/CurrentChatTabsContainer/CurrentChatTabsContainer.jsx
> +import styles from "../CurrentChatTabsContainer/CurrentChatTabsContainer.module.scss";
Correct this import

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/CurrentChatTabsContainer/CurrentChatTabsContainer.jsx
> +            <span className={styles.lightBlueEncryptedText}>
treat this as a link, because thats a accesibility issue not to have one

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/CurrentChatTabsContainer/CurrentChatTabsContainer.module.scss
> +  }
Use a mixin

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/SearchContainer/SearchContainer.module.scss
> +  align-items: center;
use mixin

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/SideMenuHeader/SideMenuHeader.jsx
> +import ProfilePicture from "../../../assets/images/profile-picture.jpeg";
use camelCase when importing images and stuff that aren't React Components

2023-08-15 14:02 UTC, nathan-hyan commented on src/components/SideMenu/SideMenuHeader/SideMenuHeader.module.scss
> +  justify-content: space-between;
Use mixins

2023-08-15 14:28 UTC, AndresEstebanGonzalez commented on src/components/SideMenu/CurrentChatTabsContainer/CurrentChatTabsContainer.jsx
> +            <span className={styles.lightBlueEncryptedText}>
Treated as a button.

2023-08-16 00:00 UTC, nathan-hyan approved these changes

2023-08-16 00:00 UTC, nathan-hyan commented on src/components/SideMenu/CurrentChatTabsContainer/CurrentChatTabsContainer.jsx
> +            <button className={styles.lightBlueEncryptedText}>
Great!

2023-08-16 00:02 UTC, merged